version: 2.0

circleci_golang: &circleci_golang
  docker:
    - image: circleci/golang:1.13.3-stretch
  working_directory: /go/src/github.com/stiyyagura0901/merge-queue-poc

jobs:
  ci_build:
    <<: *circleci_golang
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download
      - run: |
          cd /go/src/github.com/stiyyagura0901/merge-queue-poc; go build main.go
  ci_tests:
    <<: *circleci_golang
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download
      - run: |
          cd /go/src/github.com/stiyyagura0901/merge-queue-poc; go test -v ./...


workflows:
  version: 2
  build:
    jobs:
      - ci_tests
      - ci_build:
          requires:
            - ci_build
